from typing import Sequence



def splice(l: list[str], a: int, b: int, c: int) -> list[str]: ...

def decode_audio_url(string: str, user_id: int) -> str: ...

def vk_o(string: str) -> str: ...

def vk_r(string: str, i: str) -> str:...

def vk_xor(string: str, i: Sequence) -> str: ...

def vk_s_child(t: list[str], e: str) -> list[str]: ...

def vk_s(t: str, e: str) -> str: ...

def vk_i(t: str, e: str, user_id: int): ...