from typing import Any, Iterator
from vk_api.vk_api import VkApi, VkApiMethod


class VkFunction:
    def __init__(self, code: str, args:tuple= ..., clean_args:tuple=..., return_raw:bool=False) -> None: ...
    
    def __call__(self, vk: VkApi|VkApiMethod, *args: Any, **kwargs:Any): ...
    
def minify(code: str): ...

def parse_args(function_args: dict, args: Iterator, kwargs: Iterator): ...

class VkFunctionException(Exception): ...