from re import Pattern
from typing import Any
from requests.cookies import RequestsCookieJar
from requests import Request

from .vk_api import VkApi


def search_re(reg: Pattern, string: str) -> str: ...

def clear_string(s: str) -> str: ...

def get_random_id() -> int: ...

def code_from_number(prefix: str, postfix: str, number: str) -> str: ...

def sjson_dumps(*args: Any, **kwargs: Any) -> str: ...

def cookie_to_dict(cookie: RequestsCookieJar) -> dict: ...

def cookie_from_dict(d: dict) -> RequestsCookieJar: ...

def cookies_to_list(cookies: RequestsCookieJar) -> list[dict]: ...

def set_cookies_from_list(cookie_jar: RequestsCookieJar, l: dict) -> None: ...

def enable_debug_mode(vk_session: VkApi, print_content: bool=False):
    
    class DebugHTTPAdapter:
        def send(self, request: Request, **kwargs: Any) -> Request: ...